import React, { createContext, useContext, useState, useEffect, ReactNode, useMemo } from 'react';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { GlobeIcon } from 'lucide-react';

// Define all supported languages
export const LANGUAGES = {
  en: { name: 'English', nativeName: 'English' },
  hi: { name: 'Hindi', nativeName: 'हिन्दी' },
  ta: { name: 'Tamil', nativeName: 'தமிழ்' },
  te: { name: 'Telugu', nativeName: 'తెలుగు' },
  ml: { name: 'Malayalam', nativeName: 'മലയാളം' },
  kn: { name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  bn: { name: 'Bengali', nativeName: 'বাংলা' },
  gu: { name: 'Gujarati', nativeName: 'ગુજરાતી' },
  mr: { name: 'Marathi', nativeName: 'मराठी' },
  pa: { name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  ar: { name: 'Arabic', nativeName: 'العربية' },
  zh: { name: 'Chinese', nativeName: '中文' },
  fr: { name: 'French', nativeName: 'Français' },
  de: { name: 'German', nativeName: 'Deutsch' },
  es: { name: 'Spanish', nativeName: 'Español' },
  ru: { name: 'Russian', nativeName: 'Русский' },
};

// Create types for language context
type LanguageContextType = {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string, params?: Record<string, string>) => string;
  isRTL: boolean;
};

// Create translations
// Holds all translations for supported languages
export const translations: Record<string, Record<string, string>> = {
  en: {
    // Navigation & Basic UI
    'home': 'Home',
    'products': 'Products',
    'categories': 'Categories',
    'cart': 'Cart',
    'search': 'Search',
    'account': 'Account',
    'login': 'Login',
    'logout': 'Logout',
    'register': 'Register',
    'add_to_cart': 'Add to Cart',
    'buy_now': 'Buy Now',
    'price': 'Price',
    'view_cart': 'View Cart',
    'please_add_items_to_proceed': 'Please add item(s) to proceed',
    'quick_links': 'Quick links',
    'quantity': 'Quantity',
    'order_summary': 'Order Summary',
    'subtotal': 'Subtotal',
    'discount': 'Discount',
    'delivery_charges': 'Delivery Charges',
    'total': 'Total',
    'free': 'FREE',
    
    // Product Information Fields
    'description': 'Description',
    'manufacturer': 'Manufacturer',
    'salt_composition': 'Salt Composition',
    'medicine_type': 'Medicine Type',
    'stock': 'Stock',
    'introduction': 'Introduction',
    'benefits': 'Benefits',
    'how_to_use': 'How to Use',
    'safety_advice': 'Safety Advice',
    'if_miss': 'If You Miss a Dose',
    'packaging': 'Packaging',
    'packaging_type': 'Packaging Type',
    'mrp': 'MRP',
    'best_price': 'Best Price',
    'discount_percent': 'Discount',
    'views_bought': 'Views & Purchases',
    'prescription_required': 'Prescription Required',
    'label': 'Label',
    'fact_box': 'Fact Box',
    'primary_use': 'Primary Use',
    'storage': 'Storage',
    'common_side_effect': 'Common Side Effects',
    'alcohol_interaction': 'Alcohol Interaction',
    'pregnancy_interaction': 'Pregnancy Interaction',
    'lactation_interaction': 'Lactation Interaction',
    'driving_interaction': 'Driving Interaction',
    'kidney_interaction': 'Kidney Interaction',
    'liver_interaction': 'Liver Interaction',
    'manufacturer_address': 'Manufacturer Address',
    'country_of_origin': 'Country of Origin',
    'for_sale': 'For Sale',
    'q_and_a': 'Q&A',
    
    // Tab Labels
    'uses': 'Uses',
    'composition': 'Composition',
    'directions_for_use': 'Directions for Use',
    'storage_and_disposal': 'Storage and Disposal',
    'quick_tips': 'Quick Tips',
    'interactions': 'Interactions',
    'ingredients_and_benefits': 'Ingredients and Benefits',
    'similar_medicines': 'Similar Medicines',
    'frequently_bought_together': 'Frequently Bought Together',
    'in_stock': 'In Stock',
    'out_of_stock': 'Out of Stock',
    'yes': 'Yes',
    'no': 'No',
    
    // Checkout & Delivery
    'checkout': 'Checkout',
    'address': 'Address',
    'payment': 'Payment',
    'confirmation': 'Confirmation',
    'shipping_address': 'Shipping Address',
    'payment_method': 'Payment Method',
    'full_name': 'Full Name',
    'email': 'Email',
    'phone': 'Phone Number',
    'city': 'City',
    'state': 'State',
    'pincode': 'Pincode',
    'enter_full_name': 'Enter your full name',
    'enter_email': 'Enter your email',
    'enter_phone': 'Enter your phone number',
    'enter_address': 'Enter your address',
    'enter_city': 'Enter your city',
    'enter_state': 'Enter your state',
    'enter_pincode': 'Enter your pincode',
    'select_payment_method': 'Select a Payment Method',
    'credit_card': 'Credit Card',
    'debit_card': 'Debit Card',
    'upi_payment': 'UPI / Mobile Payment',
    'cash_on_delivery': 'Cash on Delivery',
    'demo_checkout_notice': 'This is a demo checkout. No actual payment will be processed.',
    'order_confirmed': 'Order Confirmed!',
    'order_id': 'Order ID',
    'thank_you_order': 'Thank you for your order. Your order has been placed successfully!',
    'email_confirmation': 'You will receive an email confirmation shortly with the details of your order.',
    'return_home': 'Return to Home',
    'continue_shopping': 'Continue Shopping',
    'delivery_available_title': 'Delivery Available',
    'delivery_available_desc': 'We deliver to your area!',
    'delivery_unavailable_title': 'Delivery Unavailable',
    'delivery_unavailable_desc': 'Sorry, we don\'t deliver to your area yet.',
    'delivery_time_message': 'Delivery typically takes 1-3 business days.',
    'delivery_unavailable_message': 'Try another pincode or select pickup from a nearby store.',
    'pincode_error_title': 'Pincode Error',
    'pincode_error_desc': 'Unable to verify pincode. Please check and try again.',
  },
  hi: {
    // Navigation & Basic UI
    'home': 'होम',
    'products': 'उत्पाद',
    'categories': 'श्रेणियाँ',
    // Pincode Checker translations
    'enter_pincode_check': 'पिनकोड दर्ज करें',
    'check': 'जाँचें',
    'cart': 'कार्ट',
    'search': 'खोज',
    'account': 'खाता',
    'login': 'लॉगिन',
    'logout': 'लॉगआउट',
    'register': 'रजिस्टर',
    'add_to_cart': 'कार्ट में जोड़ें',
    'buy_now': 'अभी खरीदें',
    'price': 'मूल्य',
    'view_cart': 'कार्ट देखें',
    'please_add_items_to_proceed': 'आगे बढ़ने के लिए कृपया आइटम जोड़ें',
    'quick_links': 'त्वरित लिंक',
    'quantity': 'मात्रा',
    'order_summary': 'आदेश सारांश',
    'subtotal': 'उप-योग',
    'discount': 'छूट',
    'delivery_charges': 'डिलीवरी शुल्क',
    'total': 'कुल',
    'free': 'मुफ्त',
    
    // Product Information Fields
    'description': 'विवरण',
    'manufacturer': 'निर्माता',
    'salt_composition': 'नमक संरचना',
    'medicine_type': 'दवा का प्रकार',
    'stock': 'स्टॉक',
    'introduction': 'परिचय',
    'benefits': 'लाभ',
    'how_to_use': 'कैसे उपयोग करें',
    'safety_advice': 'सुरक्षा सलाह',
    'if_miss': 'अगर खुराक छूट जाए तो',
    'packaging': 'पैकेजिंग',
    'packaging_type': 'पैकेजिंग प्रकार',
    'mrp': 'एमआरपी',
    'best_price': 'सबसे अच्छी कीमत',
    'discount_percent': 'छूट',
    'views_bought': 'देखे और खरीदे गए',
    'prescription_required': 'पर्चे की आवश्यकता है',
    'label': 'लेबल',
    'fact_box': 'तथ्य बॉक्स',
    'primary_use': 'प्राथमिक उपयोग',
    'storage': 'भंडारण',
    'common_side_effect': 'आम दुष्प्रभाव',
    'alcohol_interaction': 'अल्कोहल इंटरैक्शन',
    'pregnancy_interaction': 'गर्भावस्था इंटरैक्शन',
    'lactation_interaction': 'स्तनपान इंटरैक्शन',
    'driving_interaction': 'ड्राइविंग इंटरैक्शन',
    'kidney_interaction': 'किडनी इंटरैक्शन',
    'liver_interaction': 'लिवर इंटरैक्शन',
    'manufacturer_address': 'निर्माता का पता',
    'country_of_origin': 'उत्पत्ति देश',
    'for_sale': 'बिक्री के लिए',
    'q_and_a': 'प्रश्न और उत्तर',
    
    // Tab Labels
    'uses': 'उपयोग',
    'composition': 'संरचना',
    'directions_for_use': 'उपयोग के लिए निर्देश',
    'storage_and_disposal': 'भंडारण और निपटान',
    'quick_tips': 'त्वरित टिप्स',
    'interactions': 'इंटरैक्शन्स',
    'ingredients_and_benefits': 'सामग्री और लाभ',
    'similar_medicines': 'समान दवाएं',
    'frequently_bought_together': 'अक्सर एक साथ खरीदे जाते हैं',
    'in_stock': 'स्टॉक में है',
    'out_of_stock': 'स्टॉक में नहीं है',
    'yes': 'हां',
    'no': 'नहीं',
    
    // Checkout & Delivery
    'checkout': 'चेकआउट',
    'address': 'पता',
    'payment': 'भुगतान',
    'confirmation': 'पुष्टि',
    'shipping_address': 'शिपिंग पता',
    'payment_method': 'भुगतान विधि',
    'full_name': 'पूरा नाम',
    'email': 'ईमेल',
    'phone': 'फोन नंबर',
    'city': 'शहर',
    'state': 'राज्य',
    'pincode': 'पिनकोड',
    'enter_full_name': 'अपना पूरा नाम दर्ज करें',
    'enter_email': 'अपना ईमेल दर्ज करें',
    'enter_phone': 'अपना फोन नंबर दर्ज करें',
    'enter_address': 'अपना पता दर्ज करें',
    'enter_city': 'अपना शहर दर्ज करें',
    'enter_state': 'अपना राज्य दर्ज करें',
    'enter_pincode': 'अपना पिनकोड दर्ज करें',
    'select_payment_method': 'भुगतान विधि चुनें',
    'credit_card': 'क्रेडिट कार्ड',
    'debit_card': 'डेबिट कार्ड',
    'upi_payment': 'यूपीआई / मोबाइल भुगतान',
    'cash_on_delivery': 'डिलीवरी पर नकद',
    'demo_checkout_notice': 'यह एक डेमो चेकआउट है। कोई वास्तविक भुगतान प्रोसेस नहीं किया जाएगा।',
    'order_confirmed': 'आदेश की पुष्टि हो गई है!',
    'order_id': 'आदेश आईडी',
    'thank_you_order': 'आपके आदेश के लिए धन्यवाद। आपका आदेश सफलतापूर्वक हो गया है!',
    'email_confirmation': 'आपको जल्द ही अपने आदेश के विवरण के साथ एक ईमेल पुष्टिकरण प्राप्त होगा।',
    'return_home': 'होम पर वापस जाएं',
    'continue_shopping': 'खरीदारी जारी रखें',
    'delivery_available_title': 'डिलीवरी उपलब्ध',
    'delivery_available_desc': 'हम आपके क्षेत्र में डिलीवरी करते हैं!',
    'delivery_unavailable_title': 'डिलीवरी अनुपलब्ध',
    'delivery_unavailable_desc': 'क्षमा करें, हम अभी तक आपके क्षेत्र में डिलीवरी नहीं करते हैं।',
    'delivery_time_message': 'डिलीवरी आमतौर पर 1-3 कार्य दिवसों में होती है।',
    'delivery_unavailable_message': 'दूसरा पिनकोड आज़माएं या नज़दीकी स्टोर से पिकअप करें।',
    'pincode_error_title': 'पिनकोड त्रुटि',
    'pincode_error_desc': 'पिनकोड सत्यापित करने में असमर्थ। कृपया जांचें और फिर से प्रयास करें।',
  },
  ta: {
    'home': 'முகப்பு',
    'products': 'பொருட்கள்',
    'categories': 'வகைகள்',
    'cart': 'கார்ட்',
    'search': 'தேடு',
    'account': 'கணக்கு',
    'login': 'உள்நுழைய',
    'logout': 'வெளியேறு',
    'register': 'பதிவு செய்ய',
    'add_to_cart': 'கார்ட்டில் சேர்',
    'buy_now': 'இப்போது வாங்கு',
    'price': 'விலை',
    'description': 'விளக்கம்',
    'uses': 'பயன்பாடுகள்',
    'composition': 'கலவை',
    'directions_for_use': 'பயன்படுத்தும் முறை',
    'storage_and_disposal': 'சேமிப்பு மற்றும் அகற்றல்',
    'quick_tips': 'விரைவு குறிப்புகள்',
    'interactions': 'தொடர்புகள்',
    'ingredients_and_benefits': 'பொருட்கள் மற்றும் நன்மைகள்',
    'fact_box': 'உண்மை பெட்டி',
    'similar_medicines': 'இதே போன்ற மருந்துகள்',
    'frequently_bought_together': 'அடிக்கடி ஒன்றாக வாங்கப்படுகின்றன',
    'view_cart': 'கார்ட் காண்க',
    'please_add_items_to_proceed': 'தொடர பொருட்களை சேர்க்கவும்',
    'quick_links': 'விரைவு இணைப்புகள்',
    'quantity': 'அளவு',
    'order_summary': 'ஆர்டர் சுருக்கம்',
    'subtotal': 'கூட்டுத்தொகை',
    'discount': 'தள்ளுபடி',
    'delivery_charges': 'டெலிவரி கட்டணம்',
    'total': 'மொத்தம்',
    'free': 'இலவசம்',
  },
  fr: {
    // Navigation & Basic UI
    'home': 'Accueil',
    'products': 'Produits',
    'categories': 'Catégories',
    'cart': 'Panier',
    'search': 'Rechercher',
    'account': 'Compte',
    'login': 'Connexion',
    'logout': 'Déconnexion',
    'register': 'S\'inscrire',
    'add_to_cart': 'Ajouter au panier',
    'buy_now': 'Acheter maintenant',
    'price': 'Prix',
    'view_cart': 'Voir le panier',
    'please_add_items_to_proceed': 'Veuillez ajouter des articles pour continuer',
    'quick_links': 'Liens rapides',
    'quantity': 'Quantité',
    'order_summary': 'Récapitulatif de la commande',
    'subtotal': 'Sous-total',
    'discount': 'Réduction',
    'delivery_charges': 'Frais de livraison',
    'total': 'Total',
    'free': 'GRATUIT',
    
    // Product Information Fields
    'description': 'Description',
    'manufacturer': 'Fabricant',
    'salt_composition': 'Composition du sel',
    'medicine_type': 'Type de médicament',
    'stock': 'Stock',
    'introduction': 'Introduction',
    'benefits': 'Avantages',
    'how_to_use': 'Comment utiliser',
    'safety_advice': 'Conseils de sécurité',
    'if_miss': 'Si vous manquez une dose',
    'packaging': 'Emballage',
    'packaging_type': 'Type d\'emballage',
    'mrp': 'Prix maximum de vente',
    'best_price': 'Meilleur prix',
    'discount_percent': 'Pourcentage de réduction',
    'views_bought': 'Vues et achats',
    'prescription_required': 'Ordonnance requise',
    'label': 'Étiquette',
    'fact_box': 'Boîte d\'information',
    'primary_use': 'Utilisation principale',
    'storage': 'Stockage',
    'common_side_effect': 'Effets secondaires courants',
    'alcohol_interaction': 'Interaction avec l\'alcool',
    'pregnancy_interaction': 'Interaction avec la grossesse',
    'lactation_interaction': 'Interaction avec l\'allaitement',
    'driving_interaction': 'Interaction avec la conduite',
    'kidney_interaction': 'Interaction avec les reins',
    'liver_interaction': 'Interaction avec le foie',
    'manufacturer_address': 'Adresse du fabricant',
    'country_of_origin': 'Pays d\'origine',
    'for_sale': 'À vendre',
    'q_and_a': 'Questions et réponses',
    
    // Tab Labels
    'uses': 'Utilisations',
    'composition': 'Composition',
    'directions_for_use': 'Mode d\'emploi',
    'storage_and_disposal': 'Stockage et élimination',
    'quick_tips': 'Conseils rapides',
    'interactions': 'Interactions',
    'ingredients_and_benefits': 'Ingrédients et avantages',
    'similar_medicines': 'Médicaments similaires',
    'frequently_bought_together': 'Souvent achetés ensemble',
    'in_stock': 'En stock',
    'out_of_stock': 'Rupture de stock',
    'yes': 'Oui',
    'no': 'Non',
    
    // Checkout & Delivery
    'checkout': 'Paiement',
    'address': 'Adresse',
    'payment': 'Paiement',
    'confirmation': 'Confirmation',
    'shipping_address': 'Adresse de livraison',
    'payment_method': 'Méthode de paiement',
    'full_name': 'Nom complet',
    'email': 'Email',
    'phone': 'Numéro de téléphone',
    'city': 'Ville',
    'state': 'État/Région',
    'pincode': 'Code postal',
    'enter_full_name': 'Entrez votre nom complet',
    'enter_email': 'Entrez votre email',
    'enter_phone': 'Entrez votre numéro de téléphone',
    'enter_address': 'Entrez votre adresse',
    'enter_city': 'Entrez votre ville',
    'enter_state': 'Entrez votre état/région',
    'enter_pincode': 'Entrez votre code postal',
    'select_payment_method': 'Sélectionnez une méthode de paiement',
    'credit_card': 'Carte de crédit',
    'debit_card': 'Carte de débit',
    'upi_payment': 'Paiement UPI / Mobile',
    'cash_on_delivery': 'Paiement à la livraison',
    'demo_checkout_notice': 'Ceci est un paiement de démonstration. Aucun paiement réel ne sera traité.',
    'order_confirmed': 'Commande confirmée !',
    'order_id': 'Numéro de commande',
    'thank_you_order': 'Merci pour votre commande. Votre commande a été passée avec succès !',
    'email_confirmation': 'Vous recevrez bientôt une confirmation par email avec les détails de votre commande.',
    'return_home': 'Retour à l\'accueil',
    'continue_shopping': 'Continuer les achats',
    'delivery_available_title': 'Livraison disponible',
    'delivery_available_desc': 'Nous livrons dans votre région !',
    'delivery_unavailable_title': 'Livraison indisponible',
    'delivery_unavailable_desc': 'Désolé, nous ne livrons pas encore dans votre région.',
    'delivery_time_message': 'La livraison prend généralement 1 à 3 jours ouvrables.',
    'delivery_unavailable_message': 'Essayez un autre code postal ou sélectionnez le retrait dans un magasin à proximité.',
    'pincode_error_title': 'Erreur de code postal',
    'pincode_error_desc': 'Impossible de vérifier le code postal. Veuillez vérifier et réessayer.',
  },
  es: {
    // Navigation & Basic UI
    'home': 'Inicio',
    'products': 'Productos',
    'categories': 'Categorías',
    'cart': 'Carrito',
    'search': 'Buscar',
    'account': 'Cuenta',
    'login': 'Iniciar sesión',
    'logout': 'Cerrar sesión',
    'register': 'Registrarse',
    'add_to_cart': 'Añadir al carrito',
    'buy_now': 'Comprar ahora',
    'price': 'Precio',
    'view_cart': 'Ver carrito',
    'please_add_items_to_proceed': 'Por favor añada artículos para continuar',
    'quick_links': 'Enlaces rápidos',
    'quantity': 'Cantidad',
    'order_summary': 'Resumen del pedido',
    'subtotal': 'Subtotal',
    'discount': 'Descuento',
    'delivery_charges': 'Gastos de envío',
    'total': 'Total',
    'free': 'GRATIS',
    
    // Product Information Fields
    'description': 'Descripción',
    'manufacturer': 'Fabricante',
    'salt_composition': 'Composición de sal',
    'medicine_type': 'Tipo de medicina',
    'stock': 'Stock',
    'introduction': 'Introducción',
    'benefits': 'Beneficios',
    'how_to_use': 'Cómo usar',
    'safety_advice': 'Consejos de seguridad',
    'if_miss': 'Si olvida una dosis',
    'packaging': 'Empaque',
    'packaging_type': 'Tipo de empaque',
    'mrp': 'Precio máximo de venta',
    'best_price': 'Mejor precio',
    'discount_percent': 'Porcentaje de descuento',
    'views_bought': 'Vistas y compras',
    'prescription_required': 'Requiere receta',
    'label': 'Etiqueta',
    'fact_box': 'Recuadro de hechos',
    'primary_use': 'Uso principal',
    'storage': 'Almacenamiento',
    'common_side_effect': 'Efectos secundarios comunes',
    'alcohol_interaction': 'Interacción con alcohol',
    'pregnancy_interaction': 'Interacción durante el embarazo',
    'lactation_interaction': 'Interacción durante la lactancia',
    'driving_interaction': 'Interacción al conducir',
    'kidney_interaction': 'Interacción con los riñones',
    'liver_interaction': 'Interacción con el hígado',
    'manufacturer_address': 'Dirección del fabricante',
    'country_of_origin': 'País de origen',
    'for_sale': 'En venta',
    'q_and_a': 'Preguntas y respuestas',
    
    // Tab Labels
    'uses': 'Usos',
    'composition': 'Composición',
    'directions_for_use': 'Instrucciones de uso',
    'storage_and_disposal': 'Almacenamiento y eliminación',
    'quick_tips': 'Consejos rápidos',
    'interactions': 'Interacciones',
    'ingredients_and_benefits': 'Ingredientes y beneficios',
    'similar_medicines': 'Medicamentos similares',
    'frequently_bought_together': 'Comprados frecuentemente juntos',
    'in_stock': 'En stock',
    'out_of_stock': 'Agotado',
    'yes': 'Sí',
    'no': 'No',
    
    // Checkout & Delivery
    'checkout': 'Pago',
    'address': 'Dirección',
    'payment': 'Pago',
    'confirmation': 'Confirmación',
    'shipping_address': 'Dirección de envío',
    'payment_method': 'Método de pago',
    'full_name': 'Nombre completo',
    'email': 'Correo electrónico',
    'phone': 'Número de teléfono',
    'city': 'Ciudad',
    'state': 'Estado/Provincia',
    'pincode': 'Código postal',
    'enter_full_name': 'Ingrese su nombre completo',
    'enter_email': 'Ingrese su correo electrónico',
    'enter_phone': 'Ingrese su número de teléfono',
    'enter_address': 'Ingrese su dirección',
    'enter_city': 'Ingrese su ciudad',
    'enter_state': 'Ingrese su estado/provincia',
    'enter_pincode': 'Ingrese su código postal',
    'select_payment_method': 'Seleccione un método de pago',
    'credit_card': 'Tarjeta de crédito',
    'debit_card': 'Tarjeta de débito',
    'upi_payment': 'Pago UPI / Móvil',
    'cash_on_delivery': 'Pago contra entrega',
    'demo_checkout_notice': 'Este es un pago de demostración. No se procesará ningún pago real.',
    'order_confirmed': '¡Pedido confirmado!',
    'order_id': 'ID del pedido',
    'thank_you_order': '¡Gracias por su pedido. Su pedido se ha realizado con éxito!',
    'email_confirmation': 'Recibirá pronto una confirmación por correo electrónico con los detalles de su pedido.',
    'return_home': 'Volver al inicio',
    'continue_shopping': 'Continuar comprando',
    'delivery_available_title': 'Entrega disponible',
    'delivery_available_desc': '¡Entregamos en su zona!',
    'delivery_unavailable_title': 'Entrega no disponible',
    'delivery_unavailable_desc': 'Lo sentimos, aún no entregamos en su zona.',
    'delivery_time_message': 'La entrega suele tardar de 1 a 3 días hábiles.',
    'delivery_unavailable_message': 'Pruebe con otro código postal o seleccione recoger en una tienda cercana.',
    'pincode_error_title': 'Error de código postal',
    'pincode_error_desc': 'No se puede verificar el código postal. Por favor, compruebe e inténtelo de nuevo.',
  },
  ar: {
    // Navigation & Basic UI
    'home': 'الرئيسية',
    'products': 'المنتجات',
    'categories': 'الفئات',
    'cart': 'السلة',
    'search': 'بحث',
    'account': 'الحساب',
    'login': 'تسجيل الدخول',
    'logout': 'تسجيل الخروج',
    'register': 'التسجيل',
    'add_to_cart': 'أضف إلى السلة',
    'buy_now': 'اشتر الآن',
    'price': 'السعر',
    'view_cart': 'عرض السلة',
    'please_add_items_to_proceed': 'الرجاء إضافة عناصر للمتابعة',
    'quick_links': 'روابط سريعة',
    'quantity': 'الكمية',
    'order_summary': 'ملخص الطلب',
    'subtotal': 'المجموع الفرعي',
    'discount': 'الخصم',
    'delivery_charges': 'رسوم التوصيل',
    'total': 'الإجمالي',
    'free': 'مجاناً',
    
    // Product Information Fields
    'description': 'الوصف',
    'manufacturer': 'الشركة المصنعة',
    'salt_composition': 'تركيبة الملح',
    'medicine_type': 'نوع الدواء',
    'stock': 'المخزون',
    'introduction': 'مقدمة',
    'benefits': 'الفوائد',
    'how_to_use': 'كيفية الاستخدام',
    'safety_advice': 'نصائح السلامة',
    'if_miss': 'إذا فاتتك جرعة',
    'packaging': 'التعبئة',
    'packaging_type': 'نوع التعبئة',
    'mrp': 'السعر الأقصى للتجزئة',
    'best_price': 'أفضل سعر',
    'discount_percent': 'نسبة الخصم',
    'views_bought': 'المشاهدات والمشتريات',
    'prescription_required': 'تتطلب وصفة طبية',
    'label': 'ملصق',
    'fact_box': 'صندوق الحقائق',
    'primary_use': 'الاستخدام الرئيسي',
    'storage': 'التخزين',
    'common_side_effect': 'الآثار الجانبية الشائعة',
    'alcohol_interaction': 'التفاعل مع الكحول',
    'pregnancy_interaction': 'التفاعل مع الحمل',
    'lactation_interaction': 'التفاعل مع الرضاعة',
    'driving_interaction': 'التفاعل مع القيادة',
    'kidney_interaction': 'التفاعل مع الكلى',
    'liver_interaction': 'التفاعل مع الكبد',
    'manufacturer_address': 'عنوان الشركة المصنعة',
    'country_of_origin': 'بلد المنشأ',
    'for_sale': 'للبيع',
    'q_and_a': 'أسئلة وأجوبة',
    
    // Tab Labels
    'uses': 'الاستخدامات',
    'composition': 'التركيب',
    'directions_for_use': 'إرشادات الاستخدام',
    'storage_and_disposal': 'التخزين والتخلص',
    'quick_tips': 'نصائح سريعة',
    'interactions': 'التفاعلات',
    'ingredients_and_benefits': 'المكونات والفوائد',
    'similar_medicines': 'أدوية مشابهة',
    'frequently_bought_together': 'تُشترى معًا بشكل متكرر',
    'in_stock': 'متوفر',
    'out_of_stock': 'غير متوفر',
    'yes': 'نعم',
    'no': 'لا',
    
    // Checkout & Delivery
    'checkout': 'الدفع',
    'address': 'العنوان',
    'payment': 'الدفع',
    'confirmation': 'التأكيد',
    'shipping_address': 'عنوان الشحن',
    'payment_method': 'طريقة الدفع',
    'full_name': 'الاسم الكامل',
    'email': 'البريد الإلكتروني',
    'phone': 'رقم الهاتف',
    'city': 'المدينة',
    'state': 'الولاية/المنطقة',
    'pincode': 'الرمز البريدي',
    'enter_full_name': 'أدخل اسمك الكامل',
    'enter_email': 'أدخل بريدك الإلكتروني',
    'enter_phone': 'أدخل رقم هاتفك',
    'enter_address': 'أدخل عنوانك',
    'enter_city': 'أدخل مدينتك',
    'enter_state': 'أدخل ولايتك/منطقتك',
    'enter_pincode': 'أدخل الرمز البريدي',
    'select_payment_method': 'اختر طريقة الدفع',
    'credit_card': 'بطاقة ائتمان',
    'debit_card': 'بطاقة خصم',
    'upi_payment': 'دفع UPI / جوال',
    'cash_on_delivery': 'الدفع عند الاستلام',
    'demo_checkout_notice': 'هذا دفع تجريبي. لن تتم معالجة أي دفع حقيقي.',
    'order_confirmed': 'تم تأكيد الطلب!',
    'order_id': 'رقم الطلب',
    'thank_you_order': 'شكرًا لطلبك. تم تقديم طلبك بنجاح!',
    'email_confirmation': 'ستتلقى قريبًا تأكيدًا بالبريد الإلكتروني مع تفاصيل طلبك.',
    'return_home': 'العودة إلى الصفحة الرئيسية',
    'continue_shopping': 'متابعة التسوق',
    'delivery_available_title': 'التوصيل متاح',
    'delivery_available_desc': 'نحن نوصل إلى منطقتك!',
    'delivery_unavailable_title': 'التوصيل غير متاح',
    'delivery_unavailable_desc': 'نأسف، نحن لا نوصل إلى منطقتك بعد.',
    'delivery_time_message': 'يستغرق التوصيل عادة 1-3 أيام عمل.',
    'delivery_unavailable_message': 'جرب رمزًا بريديًا آخر أو اختر الاستلام من متجر قريب.',
    'pincode_error_title': 'خطأ في الرمز البريدي',
    'pincode_error_desc': 'تعذر التحقق من الرمز البريدي. يرجى التحقق والمحاولة مرة أخرى.',
  },
  de: {
    // Navigation & Basic UI
    'home': 'Startseite',
    'products': 'Produkte',
    'categories': 'Kategorien',
    'cart': 'Warenkorb',
    'search': 'Suchen',
    'account': 'Konto',
    'login': 'Anmelden',
    'logout': 'Abmelden',
    'register': 'Registrieren',
    'add_to_cart': 'In den Warenkorb',
    'buy_now': 'Jetzt kaufen',
    'price': 'Preis',
    'view_cart': 'Warenkorb anzeigen',
    'please_add_items_to_proceed': 'Bitte fügen Sie Artikel hinzu, um fortzufahren',
    'quick_links': 'Schnelllinks',
    'quantity': 'Menge',
    'order_summary': 'Bestellübersicht',
    'subtotal': 'Zwischensumme',
    'discount': 'Rabatt',
    'delivery_charges': 'Versandkosten',
    'total': 'Gesamtsumme',
    'free': 'KOSTENLOS',
    
    // Product Information Fields
    'description': 'Beschreibung',
    'manufacturer': 'Hersteller',
    'salt_composition': 'Salzzusammensetzung',
    'medicine_type': 'Medikamententyp',
    'stock': 'Lagerbestand',
    'introduction': 'Einführung',
    'benefits': 'Vorteile',
    'how_to_use': 'Anwendungshinweise',
    'safety_advice': 'Sicherheitshinweise',
    'if_miss': 'Bei verpasster Dosis',
    'packaging': 'Verpackung',
    'packaging_type': 'Verpackungsart',
    'mrp': 'Höchstverkaufspreis',
    'best_price': 'Bestpreis',
    'discount_percent': 'Rabatt',
    'views_bought': 'Aufrufe und Käufe',
    'prescription_required': 'Rezeptpflichtig',
    'label': 'Etikett',
    'fact_box': 'Faktenbox',
    'primary_use': 'Hauptanwendung',
    'storage': 'Lagerung',
    'common_side_effect': 'Häufige Nebenwirkungen',
    'alcohol_interaction': 'Wechselwirkung mit Alkohol',
    'pregnancy_interaction': 'Wechselwirkung bei Schwangerschaft',
    'lactation_interaction': 'Wechselwirkung bei Stillzeit',
    'driving_interaction': 'Wechselwirkung beim Fahren',
    'kidney_interaction': 'Wechselwirkung bei Nierenerkrankungen',
    'liver_interaction': 'Wechselwirkung bei Lebererkrankungen',
    'manufacturer_address': 'Herstelleradresse',
    'country_of_origin': 'Herkunftsland',
    'for_sale': 'Zum Verkauf',
    'q_and_a': 'Fragen und Antworten',
    
    // Tab Labels
    'uses': 'Anwendungen',
    'composition': 'Zusammensetzung',
    'directions_for_use': 'Gebrauchsanweisung',
    'storage_and_disposal': 'Lagerung und Entsorgung',
    'quick_tips': 'Schnelle Tipps',
    'interactions': 'Wechselwirkungen',
    'ingredients_and_benefits': 'Inhaltsstoffe und Vorteile',
    'similar_medicines': 'Ähnliche Medikamente',
    'frequently_bought_together': 'Wird oft zusammen gekauft',
    'in_stock': 'Auf Lager',
    'out_of_stock': 'Nicht auf Lager',
    'yes': 'Ja',
    'no': 'Nein',
    
    // Checkout & Delivery
    'checkout': 'Zur Kasse',
    'address': 'Adresse',
    'payment': 'Zahlung',
    'confirmation': 'Bestätigung',
    'shipping_address': 'Lieferadresse',
    'payment_method': 'Zahlungsmethode',
    'full_name': 'Vollständiger Name',
    'email': 'E-Mail',
    'phone': 'Telefonnummer',
    'city': 'Stadt',
    'state': 'Bundesland/Region',
    'pincode': 'Postleitzahl',
    'enter_full_name': 'Geben Sie Ihren vollständigen Namen ein',
    'enter_email': 'Geben Sie Ihre E-Mail-Adresse ein',
    'enter_phone': 'Geben Sie Ihre Telefonnummer ein',
    'enter_address': 'Geben Sie Ihre Adresse ein',
    'enter_city': 'Geben Sie Ihre Stadt ein',
    'enter_state': 'Geben Sie Ihr Bundesland/Ihre Region ein',
    'enter_pincode': 'Geben Sie Ihre Postleitzahl ein',
    'select_payment_method': 'Wählen Sie eine Zahlungsmethode',
    'credit_card': 'Kreditkarte',
    'debit_card': 'Debitkarte',
    'upi_payment': 'UPI / Mobile Zahlung',
    'cash_on_delivery': 'Zahlung bei Lieferung',
    'demo_checkout_notice': 'Dies ist eine Demo-Kasse. Es wird keine echte Zahlung verarbeitet.',
    'order_confirmed': 'Bestellung bestätigt!',
    'order_id': 'Bestellnummer',
    'thank_you_order': 'Vielen Dank für Ihre Bestellung. Ihre Bestellung wurde erfolgreich aufgegeben!',
    'email_confirmation': 'Sie erhalten in Kürze eine E-Mail-Bestätigung mit den Details Ihrer Bestellung.',
    'return_home': 'Zurück zur Startseite',
    'continue_shopping': 'Weiter einkaufen',
    'delivery_available_title': 'Lieferung verfügbar',
    'delivery_available_desc': 'Wir liefern in Ihre Gegend!',
    'delivery_unavailable_title': 'Lieferung nicht verfügbar',
    'delivery_unavailable_desc': 'Entschuldigung, wir liefern noch nicht in Ihre Gegend.',
    'delivery_time_message': 'Die Lieferung dauert in der Regel 1-3 Werktage.',
    'delivery_unavailable_message': 'Versuchen Sie es mit einer anderen Postleitzahl oder wählen Sie die Abholung in einem nahegelegenen Geschäft.',
    'pincode_error_title': 'Postleitzahl-Fehler',
    'pincode_error_desc': 'Postleitzahl konnte nicht überprüft werden. Bitte überprüfen Sie und versuchen Sie es erneut.',
  },
  zh: {
    // Navigation & Basic UI
    'home': '首页',
    'products': '产品',
    'categories': '分类',
    'cart': '购物车',
    'search': '搜索',
    'account': '账户',
    'login': '登录',
    'logout': '登出',
    'register': '注册',
    'add_to_cart': '加入购物车',
    'buy_now': '立即购买',
    'price': '价格',
    'view_cart': '查看购物车',
    'please_add_items_to_proceed': '请添加商品以继续',
    'quick_links': '快速链接',
    'quantity': '数量',
    'order_summary': '订单摘要',
    'subtotal': '小计',
    'discount': '折扣',
    'delivery_charges': '配送费',
    'total': '总计',
    'free': '免费',
    
    // Product Information Fields
    'description': '描述',
    'manufacturer': '制造商',
    'salt_composition': '盐成分',
    'medicine_type': '药品类型',
    'stock': '库存',
    'introduction': '简介',
    'benefits': '益处',
    'how_to_use': '如何使用',
    'safety_advice': '安全建议',
    'if_miss': '如果错过剂量',
    'packaging': '包装',
    'packaging_type': '包装类型',
    'mrp': '最高零售价',
    'best_price': '最优价格',
    'discount_percent': '折扣',
    'views_bought': '浏览和购买',
    'prescription_required': '需要处方',
    'label': '标签',
    'fact_box': '事实框',
    'primary_use': '主要用途',
    'storage': '储存',
    'common_side_effect': '常见副作用',
    'alcohol_interaction': '酒精相互作用',
    'pregnancy_interaction': '怀孕相互作用',
    'lactation_interaction': '哺乳相互作用',
    'driving_interaction': '驾驶相互作用',
    'kidney_interaction': '肾脏相互作用',
    'liver_interaction': '肝脏相互作用',
    'manufacturer_address': '制造商地址',
    'country_of_origin': '原产国',
    'for_sale': '出售',
    'q_and_a': '问答',
    
    // Tab Labels
    'uses': '用途',
    'composition': '成分',
    'directions_for_use': '使用说明',
    'storage_and_disposal': '储存和处理',
    'quick_tips': '快速提示',
    'interactions': '相互作用',
    'ingredients_and_benefits': '成分和益处',
    'similar_medicines': '类似药品',
    'frequently_bought_together': '经常一起购买',
    'in_stock': '有库存',
    'out_of_stock': '缺货',
    'yes': '是',
    'no': '否',
    
    // Checkout & Delivery
    'checkout': '结账',
    'address': '地址',
    'payment': '付款',
    'confirmation': '确认',
    'shipping_address': '送货地址',
    'payment_method': '付款方式',
    'full_name': '全名',
    'email': '电子邮件',
    'phone': '电话号码',
    'city': '城市',
    'state': '州/省',
    'pincode': '邮政编码',
    'enter_full_name': '输入您的全名',
    'enter_email': '输入您的电子邮件',
    'enter_phone': '输入您的电话号码',
    'enter_address': '输入您的地址',
    'enter_city': '输入您的城市',
    'enter_state': '输入您的州/省',
    'enter_pincode': '输入您的邮政编码',
    'select_payment_method': '选择付款方式',
    'credit_card': '信用卡',
    'debit_card': '借记卡',
    'upi_payment': 'UPI / 移动支付',
    'cash_on_delivery': '货到付款',
    'demo_checkout_notice': '这是演示结账。不会处理实际付款。',
    'order_confirmed': '订单已确认！',
    'order_id': '订单编号',
    'thank_you_order': '感谢您的订单。您的订单已成功下单！',
    'email_confirmation': '您将很快收到一封包含订单详情的确认电子邮件。',
    'return_home': '返回首页',
    'continue_shopping': '继续购物',
    'delivery_available_title': '可送货',
    'delivery_available_desc': '我们可以送货到您的地区！',
    'delivery_unavailable_title': '无法送货',
    'delivery_unavailable_desc': '抱歉，我们尚未送货到您的地区。',
    'delivery_time_message': '送货通常需要1-3个工作日。',
    'delivery_unavailable_message': '尝试其他邮政编码或从附近商店选择取货。',
    'pincode_error_title': '邮政编码错误',
    'pincode_error_desc': '无法验证邮政编码。请检查并重试。',
  },
};

// Create context
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Create provider
export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  // Try to get language from localStorage, default to English
  const [language, setLanguageState] = useState<string>(() => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem('language') || 'en';
    }
    return 'en';
  });

  // Set language and save to localStorage
  const setLanguage = (lang: string) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang);
    }
  };

  // Translation function
  const t = (key: string): string => {
    if (translations[language] && translations[language][key]) {
      return translations[language][key];
    }
    // Fallback to English
    if (translations['en'] && translations['en'][key]) {
      return translations['en'][key];
    }
    // If no translation is found, return the key
    return key;
  };

  // Set language based on IP location when component mounts
  useEffect(() => {
    // Import dynamically to avoid server-side rendering issues
    import('../services/location-service').then(({ setLanguageBasedOnLocation }) => {
      // Set language based on IP location (only if not already set by user)
      setLanguageBasedOnLocation(setLanguage);
    }).catch(error => {
      console.error('Failed to load location service:', error);
    });
  }, []); // Empty dependency array - only run on mount

  // Get RTL status
  const isRTL = useMemo(() => {
    // RTL languages list
    const rtlLanguages: string[] = ['ar'];
    return rtlLanguages.includes(language);
  }, [language]);

  // Apply language direction for RTL languages
  useEffect(() => {
    if (isRTL) {
      document.documentElement.dir = 'rtl';
      document.documentElement.lang = language;
    } else {
      document.documentElement.dir = 'ltr';
      document.documentElement.lang = language;
    }
  }, [language, isRTL]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Create hook for easy access to context
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Language switcher component
const LanguageSwitcher: React.FC = () => {
  const { language, setLanguage } = useLanguage();

  const handleLanguageChange = (lang: string) => {
    setLanguage(lang);
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost" size="icon" className="text-gray-700 hover:bg-gray-100 rounded-full">
          <GlobeIcon className="h-5 w-5" />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-[180px]">
        {Object.keys(LANGUAGES).map((lang) => (
          <DropdownMenuItem
            key={lang}
            className={`flex items-center ${language === lang ? 'font-bold bg-gray-100' : ''}`}
            onClick={() => handleLanguageChange(lang)}
          >
            <span className="w-8">{lang.toUpperCase()}</span>
            <span className="ml-2">{LANGUAGES[lang as keyof typeof LANGUAGES].nativeName}</span>
          </DropdownMenuItem>
        ))}
      </DropdownMenuContent>
    </DropdownMenu>
  );
};

export default LanguageSwitcher;